const fs = require("fs");
const { builtinModules } = require("module");
const esbuild = require("esbuild");

const production = process.argv.includes("--production");
const watch = process.argv.includes("--watch");
const banner = "/* Generated by esbuild. Source: https://github.com/extzzy/meeting-tools */";

const options = {
  banner: { js: banner },
  entryPoints: ["src/plugin.js"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((moduleName) => `node:${moduleName}`)
  ],
  format: "cjs",
  platform: "node",
  target: "es2021",
  charset: "utf8",
  legalComments: "none",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  outfile: "main.js"
};

async function build() {
  if (watch) {
    const context = await esbuild.context(options);
    await context.watch();
    return;
  }

  await esbuild.build(options);
  const bytes = fs.statSync(options.outfile).size;
  console.log(`Built ${options.outfile} (${bytes} bytes, ${production ? "production/minified" : "development"})`);
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});
